---
- name: Install Packages
  xbps:
    pkg: openntpd
    state: present

- name: Configure Daemon
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - openntp

- name: Configure Alternatives Group
  command: xbps-alternatives -s openntpd -g ntpd
  changed_when: false

- name: Install Firewall Rules
  template:
    src: ntp.rules.j2
    dest: /etc/iptables.d/ntp.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
